version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      go-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directories:
      - "/tools"
    schedule:
      interval: weekly
      day: tuesday
    groups:
      go-tool-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
    groups:
      action-updates:
        update-types:
          - "minor"
          - "patch"
