name: Lint, test, and build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: go-build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # these aliases make sure to test both latest and previous minor 
        # versions.
        go-version-alias: ["stable", "oldstable"]
    steps:
      - uses: actions/checkout@v4
      # Disable the builtin caching since it uses the hash of the go.sum file
      # to determine if the cache is valid. This is not ideal since the go.sum
      # file is updated every time a new version of a dependency is downloaded.
      # Not when your code changes.
      - name: Set up Golang ${{ matrix.go-version-alias }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version-alias }}
          cache: false
      # Use restore-keys to always use a cache that was created with the same
      # prefix.
      - name: Cache go modules and the buildcache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-build-${{ github.sha }}
          restore-keys: go-build-
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./... -coverprofile=coverage.out
      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o coverage.html
      - name: Upload coverega report
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage-report-${{ matrix.go-version-alias }}
          path: coverage.html
