name: Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version-alias: [ "stable", "oldstable" ]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go-version-alias }}

      - name: Run unit tests with coverage
        run: make unittest-json

      - name: Publish unit test results
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: always()
        with:
          name: Unit Tests
          path: build/unit-test-output.json
          reporter: golang-json
          fail-on-error: "false"

      - name: Generate coverage report
        if: always()
        run: |
          if [ -f build/coverage.out ]; then
            make coverage-report | grep "^### Code Coverage:" >> "$GITHUB_STEP_SUMMARY" || true
          fi

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: go-coverage-report-${{ github.sha }}
          path: build/coverage.html
