name: Main branch protection

run-name: "Main branch protection: ${{ github.event.head_commit.message }}"

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Should prevent concurrency on a per-branch basis.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/callable-test.yaml
    secrets: inherit

  build:
    uses: ./.github/workflows/callable-build.yaml
    secrets: inherit
